### ISSUE TITLE
Uncaught ValueError when adding a non-JSON blueprint

### ISSUE THREAD

**Issue by dmtucker** [dmtucker/yaas#20]
```
$ yaas blueprint add README.md 
Traceback (most recent call last):
  File "/usr/local/bin/yaas", line 9, in <module>
    load_entry_point('yaas==0.0.1', 'console_scripts', 'yaas')()
  File "/usr/local/lib/python2.7/dist-packages/yaas-0.0.1-py2.7.egg/yaas/__main__.py", line 75, in main
    commands[args.command](subparsers.choices[args.command], extra)
  File "/usr/local/lib/python2.7/dist-packages/yaas-0.0.1-py2.7.egg/yaas/blueprint.py", line 30, in command
    extra)
  File "/usr/local/lib/python2.7/dist-packages/yaas-0.0.1-py2.7.egg/yaas/blueprint.py", line 48, in _add
    blueprint = json.loads(blueprint)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Tracebacks should only show when a bug exists.

**Comment by dmtucker** [comment]
This also occurs when a JSON file is specified but does not have a `blueprint_name`:

```
$ yaas blueprint add blueprints/empty.json 
Traceback (most recent call last):
  File "/usr/local/bin/yaas", line 9, in <module>
    load_entry_point('yaas==0.0.1', 'console_scripts', 'yaas')()
  File "/usr/local/lib/python2.7/dist-packages/yaas-0.0.1-py2.7.egg/yaas/__main__.py", line 75, in main
    commands[args.command](subparsers.choices[args.command], extra)
  File "/usr/local/lib/python2.7/dist-packages/yaas-0.0.1-py2.7.egg/yaas/blueprint.py", line 30, in command
    extra)
  File "/usr/local/lib/python2.7/dist-packages/yaas-0.0.1-py2.7.egg/yaas/blueprint.py", line 52, in _add
    name=blueprint['Blueprints']['blueprint_name'])),
KeyError: 'blueprint_name'
```
